
---
title: "Legal document processing"
author: "Xia YIwei, Nemo"
date: "Sunday, January 01, 2017"
output: html_document
---

#Chinese legal documents processing

In the year 2014, the Chinese supreme people's court has release a **[document](http://www.chinacourt.org/article/detail/2013/11/id/1152212.shtml)** to collect and publish all the sentence documents made by court at each level in China.  

Some useful tools are needed to analyzing those Chinese document. Hence the aim of current R package  

Current R package relies on [Rwordseg](https://github.com/lijian13/Rwordseg) package made by Lijian



##1.Websites of legal documents
* [Offical website](http://wenshu.court.gov.cn/)
* [OpenLaw](http://openlaw.cn/)

##2.Aims 
* Develop useful R functions to do the Chinese word process 
* Package those functions into Github
* For general Chinese word processing  

##3.Developed functions
* Some Basic functions
  Check exist
*  cnextract  
Extract from A to B,  position A+1 to b  


* Chinese words to date/number
* Convert Chinese number to Arabic Number

## 4.Useful links

[how to write R package](http://cos.name/2011/05/write-r-packages-like-a-ninja/)  
[how source file in GitHub](https://github.com/opetchey/RREEBES/wiki/Reading-data-and-code-from-an-online-github-repository)


## 5.install all the functions
```{r eval = FALSE}

library(RCurl)

#install the read all function in my github repostroies
script <- getURL("https://github.com/xxxw567/R-Chinese-Word-Processing/blob/master/fun_install_github.R", ssl.verifypeer = FALSE)
eval(parse(text = script))
 
# install all the function in my repostroies

fun_install_github("https://github.com/xxxw567/R-Chinese-Word-Processing/tree/master/R")

```

